<?php 

$home_desktop_static_images = array();
$home_mobile_static_images = array();

$home_desktop_static_url = array();
$home_mobile_static_url = array();

$images = $block->getHomeImages();

foreach($images as $item)
{
	if(strpos($item->getImageIdentifier(), 'desktop_static_block')!==false)
	{
        $home_desktop_static_images[$item->getImageIdentifier()] = $item->getFilename();
        $home_desktop_static_url[$item->getImageIdentifier()] = $item->getUrl();
	}
    if(strpos($item->getImageIdentifier(), 'mobile_static_block')!==false)
    {
        $mobile_desktop_static_images[$item->getImageIdentifier()] = $item->getFilename();
        $home_mobile_static_url[$item->getImageIdentifier()] = $item->getUrl();
    }
}
?>	

<div id="home_mobile">
<div class="row">
<div class="slider autoplay">
<?php    
    foreach($block->getHomeImages() as $item)
    {
        if(strpos($item->getImageIdentifier(), 'home_carousel_mobile')!==false)
        {
            ?>      
                <div><div class="image"><a href="<?php echo $item->getUrl(); ?>"><img src="pub/media/home/<?php echo $item->getFilename(); ?>"/></a></div></div>       
            <?php
        }
    }
?>
</div>
</div>
<div class="row">
    <div class="col-xs-12 home-cat-block">
      <a href="<?php echo $home_mobile_static_url['mobile_static_block_1']; ?>"><img src="pub/media/home/<?php echo $mobile_desktop_static_images['mobile_static_block_1']; ?>" /></a>
    </div>
</div>
<div class="row">
    <div class="col-xs-6 home-cat-block">
      <a href="<?php echo $home_mobile_static_url['mobile_static_block_2_1']; ?>"><img src="pub/media/home/<?php echo $mobile_desktop_static_images['mobile_static_block_2_1']; ?>" /></a>
    </div>
    <div class="col-xs-6 home-cat-block">
      <a href="<?php echo $home_mobile_static_url['mobile_static_block_2_2']; ?>"><img src="pub/media/home/<?php echo $mobile_desktop_static_images['mobile_static_block_2_2']; ?>" /></a>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 home-cat-block">
      <a href="<?php echo $home_mobile_static_url['mobile_static_block_3']; ?>"><img src="pub/media/home/<?php echo $mobile_desktop_static_images['mobile_static_block_3']; ?>" /></a>
    </div>
</div>
<div class="row">
    <div class="col-xs-6 home-cat-block">
      <a href="<?php echo $home_mobile_static_url['mobile_static_block_4_1']; ?>"><img src="pub/media/home/<?php echo $mobile_desktop_static_images['mobile_static_block_4_1']; ?>" /></a>
    </div>
    <div class="col-xs-6 home-cat-block">
      <a href="<?php echo $home_mobile_static_url['mobile_static_block_4_2']; ?>"><img src="pub/media/home/<?php echo $mobile_desktop_static_images['mobile_static_block_4_2']; ?>" /></a>
    </div>
</div>
</div>
<div id="home_desktop">
<div class="row">
<div class="slider autoplay">
<?php    
    foreach($block->getHomeImages() as $item)
    {
    	if(strpos($item->getImageIdentifier(), 'home_carousel_desktop')!==false)
    	{
    		?>		
    			<div><div class="image"><a href="<?php echo $item->getUrl(); ?>"><img src="pub/media/home/<?php echo $item->getFilename(); ?>"/></a></div></div>		
    		<?php
    	}
    }
?>
</div>
</div>
<div class="row">
    <div class="col-xs-6 home-cat-block">
      <a href="<?php echo $home_desktop_static_url['desktop_static_block_1_1']; ?>"><img src="pub/media/home/<?php echo $home_desktop_static_images['desktop_static_block_1_1']; ?>" /></a>
    </div>
    <div class="col-xs-6 home-cat-block">
        <a href="<?php echo $home_desktop_static_url['desktop_static_block_1_2']; ?>"><img src="pub/media/home/<?php echo $home_desktop_static_images['desktop_static_block_1_2']; ?>" /></a>
    </div>
</div>
<div class="row">
    <div class="col-xs-8 home-cat-block">
        <a href="<?php echo $home_desktop_static_url['desktop_static_block_2_1']; ?>"><img src="pub/media/home/<?php echo $home_desktop_static_images['desktop_static_block_2_1']; ?>" /></a>
    </div>
    <div class="col-xs-4 home-cat-block">
        <a href="<?php echo $home_desktop_static_url['desktop_static_block_2_2']; ?>"><img src="pub/media/home/<?php echo $home_desktop_static_images['desktop_static_block_2_2']; ?>" /></a>
    </div>
</div>
<div class="row">
    <div class="col-xs-4 home-cat-block">
        <a href="<?php echo $home_desktop_static_url['desktop_static_block_3_1']; ?>"><img src="pub/media/home/<?php echo $home_desktop_static_images['desktop_static_block_3_1']; ?>" /></a>
    </div>
    <div class="col-xs-4 home-cat-block">
        <a href="<?php echo $home_desktop_static_url['desktop_static_block_3_2']; ?>"><img src="pub/media/home/<?php echo $home_desktop_static_images['desktop_static_block_3_2']; ?>" /></a>
    </div>
    <div class="col-xs-4 home-cat-block">
        <a href="<?php echo $home_desktop_static_url['desktop_static_block_3_3']; ?>"><img src="pub/media/home/<?php echo $home_desktop_static_images['desktop_static_block_3_3']; ?>" /></a>
    </div>
    <div class="col-xs-8 home-cat-block">
        <a href="<?php echo $home_desktop_static_url['desktop_static_block_3_4']; ?>"><img src="pub/media/home/<?php echo $home_desktop_static_images['desktop_static_block_3_4']; ?>" /></a>
    </div>
</div>
</div>