<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>
<?php if ($_attributeValue): ?>
<div class="product info detailed">
                <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
                   <div class="data item title"
                     aria-labeledby="tab-label-description-title"
                     data-role="collapsible" id="tab-label-description">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#product-description"
                       id="tab-label-product-description-title">
                        Product Features</a>
                </div>
                <div class="data item content" id="product-description" data-role="content">
                    <div class="product attribute description">
        <div class="product attribute <?= /* @escapeNotVerified */ $_className ?>">
    <?php if ($renderLabel): ?><strong class="type"><?= /* @escapeNotVerified */ $_attributeLabel ?></strong><?php endif; ?>
    <div class="value" <?= /* @escapeNotVerified */ $_attributeAddAttribute ?>><?= /* @escapeNotVerified */ $_attributeValue ?></div>
</div>
</div>
                </div>
                  <div class="data item title"
                     aria-labeledby="tab-label-delivery-title"
                     data-role="collapsible" id="tab-label-delivery">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#delivery"
                       id="tab-label-delivery-title">
                       Delivery &amp; Returns</a>
                </div>
                <div class="data item content" id="delivery" data-role="content"><?php 
    echo $block->getLayout()
               ->createBlock('Magento\Cms\Block\Block')
               ->setBlockId('delivery_product')
               ->toHtml();
?></div></div></div>	
<?php endif; ?>