<?php // $block->getBlockHtml('formkey') ?>
<fieldset class="admin__fieldset">

    <div class="admin__field">
        <div class="admin__field-label">
            <label for="number">
                <span><?php echo __('AliExpress Url') ?></span>
            </label>
        </div>

        <div class="admin__field-control">
            <input type="text" id="ali_url"
                   name="ali_url" value=""
                   class="admin__control-text">
        </div>
    </div>

    <div class="admin__field">
        <div class="admin__field-label">
            <label for="clear_current">
                <span><?php echo __('Clear current images before import') ?></span>
            </label>
        </div>

        <div class="admin__field-control">
            <input type="checkbox" id="clear_current" name="clear_current" value="1" />
        </div>
    </div>

    <div class="admin__field">

        <div class="admin__field-label">
        </div>

        <div class="admin__field-control">

            <button id="import_images" type="button" class="action submit primary"
                    title="<?php echo __('Scan Images') ?>">
                <span><?php echo __('Scan Images') ?></span>
            </button>

            <button id="clear_images" type="button" class="action-basic"
                    title="<?php echo __('Clear Scanned Images') ?>">
                <span><?php echo __('Clear Scanned Images') ?></span>
            </button>

        </div>

</fieldset>
<span id="ripped_images_message"></span>
<style>
    #image_list > img {
        float: left;
        margin-right: 10px;
    }
</style>
<div id="image_list">
    <?php
    for ($x = 0; $x < 6; $x++) {
        echo "<img src='' id='image_$x' width='75' height='75' style='display:none;' />";
    }
    ?>
</div>
<script>
    require([
        'jquery',
        'prototype'
    ], function ($) {

        $('#import_images').click(function () {
            var params = {
                url: $("#ali_url").val(),
                checked: $('#clear_current').prop('checked')
            };
            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                onCreate: function () {
                    $('#image_1').attr('src', '');
                    var body = $('body').loader();
                    body.loader('show');
                },
                onSuccess: function (transport) {
                    var body = $('body').loader();
                    body.loader('hide');
                    for (i = 0; i < 6; i++) {
                        $('#image_' + i).css('display', 'none');
                    }
                    var resultText = '';
                    if (transport.status > 200) {
                        resultText = transport.statusText;
                    } else {
                        var response = JSON.parse(transport.responseText);
                        resultText = response.message;
                        var errorText = response.errorMessage;
                    }
                    if (errorText) {
                        $('#ripped_images_message').text(errorText);
                    } else {
                        var imgArray = resultText.split('|');
                        imgArray.forEach(loopFunction);

                        function loopFunction(item, index) {
                            $('#image_' + index).attr('src', item).css('display', 'block');
                        }
                    }
                }
            });
        });
        $('#clear_images').click(function () {
            var params = [];
            new Ajax.Request('<?php echo $block->getClearUrl() ?>', {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                onCreate: function () {
                    for (i = 0; i < 6; i++) {
                        $('#image_' + i).css('display', 'none');
                    }
                },
                onSuccess: function (transport) {
                    var resultText = '';
                    if (transport.status > 200) {
                        resultText = transport.statusText;
                    } else {
                        var response = JSON.parse(transport.responseText);
                        resultText = response.message;
                        var errorText = response.errorMessage;
                    }
                }
            });
        });
    });
</script>
