<div class="product info detailed">
                <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
                   <div class="data item title"
                     aria-labeledby="tab-label-description-title"
                     data-role="collapsible" id="tab-label-description">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#product-description"
                       id="tab-label-product-description-title">
                        Product Features</a>
                </div>
                <div class="data item content" id="product-description" data-role="content">
                    <div class="product attribute description">
        <div class="value" ><p>Materials: Brass Base Metal, Rhodium Plated, Blue Enamel, Orange Enamel, Purple Enamel, Pink Enamel, Green Enamel</p>
<p>Dimensions: </p></div>
</div>
                </div>
                  <div class="data item title"
                     aria-labeledby="tab-label-delivery-title"
                     data-role="collapsible" id="tab-label-delivery">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#delivery"
                       id="tab-label-delivery-title">
                       Delivery &amp; Returns</a>
                </div>
                <div class="data item content" id="delivery" data-role="content"><p><strong>Standard UK Delivery</strong> (3-4 days) is FREE on orders over &pound;70, or just &pound;2.99 otherwise.</p>
<p><strong>Next Working Day Delivery</strong> is &pound;4.99 for all orders. Order before 6pm&nbsp;Monday to Friday for delivery the following day, including Saturday. <strong><br /></strong></p>
<p><span style="font-size: x-small; color: #999999;"><em>*Orders with next day delivery placed after 6pm on Friday will be delivered on Tuesday, as no parcels are dispatched on the weekend.</em></span></p>
<p><strong>Click &amp; Collect</strong> is &pound;3.99 for all orders.</p>
<p><strong>International Delivery</strong> is available to most countries worldwide. For full details of all our available delivery services view our <a href="/delivery">delivery information page.</a></p>
<p><strong>Returns</strong>&nbsp;- You can return items within 14 days of receiving your&nbsp;order for a refund. For more information on our returns policy, please visit our <a href="/returns">returns information page.</a></p></div></div></div>