<div class="promo_row row">
<div class="promo">
	<?php 
    echo $block->getLayout()
               ->createBlock('Magento\Cms\Block\Block')
               ->setBlockId('promo_banner1')
               ->toHtml();
?>
</div>
<div class="promo">
	<?php 
    echo $block->getLayout()
               ->createBlock('Magento\Cms\Block\Block')
               ->setBlockId('promo_banner2')
               ->toHtml();
?>
</div>
<div class="promo">
	<?php 
    echo $block->getLayout()
               ->createBlock('Magento\Cms\Block\Block')
               ->setBlockId('promo_banner3')
               ->toHtml();
?>
</div>
</div>